[Week3] Jeonghoon
SSAFY0916/Algorithm_Study_Java1 pull request #11
Opened 2023-02-24 01:07 UTC by Jeong-Hoon-Yang

2023-02-24 07:01 UTC, Lee-Jiseung reviewed
수고하셨습니다!

2023-02-24 07:01 UTC, Lee-Jiseung commented on WEEK3/BOJ_23288/jeonghoon.java
> +    public static void roll(int direction) {
curDir이 전역변수로 선언되어 있어서 파라미터로 넘겨주지 않아도 될 것 같습니다

2023-02-24 08:34 UTC, Jeong-Hoon-Yang commented on WEEK3/BOJ_2146/jeonghoon.java
> +                    q.add(new Pair(nextRow, nextCol, len + 1));
좋은 방법인 것 같아요! 감사합니다 :)

2023-02-26 12:43 UTC, YeonwooLee requested changes

2023-03-02 04:50 UTC, merged